CREATE TABLE `mentorship_forum`.`teachers` (
  `sap_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `department` VARCHAR(255) NOT NULL,
  `designation` VARCHAR(255) NOT NULL,
  `subjects` VARCHAR(255) NOT NULL,
  `phone` DOUBLE UNSIGNED NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`sap_id`),
  UNIQUE INDEX `sap_id_UNIQUE` (`sap_id` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `address_UNIQUE` (`address` ASC));
